version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Cổng AMQP
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: skillsharp
      RABBITMQ_DEFAULT_PASS: Skillsharp@123
